<?php

namespace OC\PlatformBundle\Repository;


use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{

    public function myFindAll(){
        return $this->createQueryBuilder('a')->getQuery()->getResult();
    }

    public function myFindOne($id){
        $queryBuilder = $this->_em->createQueryBuilder('a');
        $queryBuilder->where('a.id = :id')->setParameter('id',$id);
        return $queryBuilder->getQuery()->getResult();
    }

    public function findByAuthorAndDate($author, $date){
        $queryBuilder = $this->_em->createQueryBuilder('a');
        $queryBuilder->where('a.author = :author')->setParameter('author', $author)
            ->andWhere('a.date < :date')->setParameter('date',$date)
            ->orderBy('a.date', 'DESC');
        return $queryBuilder->getQuery()->getResult();
    }

    public function whereCurrentYear(QueryBuilder $queryBuilder){
        $queryBuilder->andWhere('a.date BETWEEN :start AND :end')
            ->setParameter('start', new \DateTime(date('Y').'-01-01'))
            ->setParameter('end',new \Datetime(date('Y').'-12-31'));
    }

    public function myFind(){
        $queryBuilder = $this->_em->createQueryBuilder('a');
        $queryBuilder->where('a.author = :author')->setParameter('author','Alexandre');
        $this->whereCurrentYear($queryBuilder);
        $queryBuilder->orderBy('a.date', 'DESC');
        return $queryBuilder->getQuery()->getResult();
    }


    public function getAdvertWithCategories(array $categoryNames){
        $qb = $this->createQueryBuilder('a');
        $qb->innerJoin('a.categories', 'c')->addSelect('c');
        $qb->where($qb->expr()->in('c.name', $categoryNames));
        return $qb->getQuery()->getResult();
    }

}
