<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
    public function getAdverts(){
        $qb = $this->createQueryBuilder('a')
            ->leftJoin('a.image','i')->addSelect('i')
            ->leftJoin('a.categories','c')->addSelect('c')
            ->leftJoin('a.advertSkills','advs')->addSelect('advs')
            ->orderBy('a.date', 'desc');
        return $qb;
    }

    // return a Query Builder selecting every advert (with advert skills and categories)
    // that has no application at all
    public function getAdvertsWithoutApplicationQueryBuilder(){
        $qb = $this->createQueryBuilder('a')
            ->leftJoin('a.advertSkills','advs')->addSelect('advs')
            ->leftJoin('a.categories','c')->addSelect('c')
            ->where('a.nbApplications = 0');
        return $qb;
    }


    // unused function but interesting example of expr() use =>
    public function getAdvertWithCategories(array $categoryNames){
        $qb = $this->createQueryBuilder('a');
        $qb->innerJoin('a.categories', 'c')->addSelect('c');
        $qb->where($qb->expr()->in('c.name', $categoryNames));
        return $qb->getQuery()->getResult();
    }

}
